### Importar bases de dados (Excel)
### Criar os DataFrames referentes à cada base

In [33]:
import pandas as pd

# importar arquivos e criar DataFrames

df_funcionarios = pd.read_excel("funcionarios.xlsx")
df_historico_salarios = pd.read_excel("historico_salarios.xlsx")
df_setores = pd.read_excel("setores.xlsx")

In [34]:
df_funcionarios.head()

   IdFuncionario     Nome  IdSetor  Salario  Idade
0              1      Ana        1     4500     25
1              2    Bruno        2     6000     30
2              3   Carlos        1     4800     28
3              4    Diana        3     7500     35
4              5  Eduardo        2     5200     40

### Exibir Nome e Salário da base de funcionários

In [35]:
print(df_funcionarios[["Nome", "Salario"]])

       Nome  Salario
0       Ana     4500
1     Bruno     6000
2    Carlos     4800
3     Diana     7500
4   Eduardo     5200
5  Fernanda     4000

### Filtrar funcionários com salário acima de 5 mil

In [36]:
print(df_funcionarios[df_funcionarios["Salario"] > 5000])

   IdFuncionario     Nome  IdSetor  Salario  Idade
1              2    Bruno        2     6000     30
3              4    Diana        3     7500     35
4              5  Eduardo        2     5200     40

### Merge entre funcionários e setores (juntar tabelas)

In [52]:
# União das duas tabelas em uma apenas - tem que usar uma coluna de referência
# vamos usar o ID, como referência, porque tem nas duas tabelas

df_funcionarios_setor = df_funcionarios.merge(df_setores, on="IdSetor")

In [38]:
# para ver a tabela nova

df_funcionarios_setor

   IdFuncionario      Nome  IdSetor  Salario  Idade             Setor
0              1       Ana        1     4500     25  Recursos Humanos
1              2     Bruno        2     6000     30        Tecnologia
2              3    Carlos        1     4800     28  Recursos Humanos
3              4     Diana        3     7500     35            Vendas
4              5   Eduardo        2     5200     40        Tecnologia
5              6  Fernanda        3     4000     26            Vendas

In [39]:
# exibir as 3 colunas nome, setor e salário
df_funcionarios_setor[["Nome", "Setor", "Salario"]]

       Nome             Setor  Salario
0       Ana  Recursos Humanos     4500
1     Bruno        Tecnologia     6000
2    Carlos  Recursos Humanos     4800
3     Diana            Vendas     7500
4   Eduardo        Tecnologia     5200
5  Fernanda            Vendas     4000

### Adicionar novos funcionários (concat)

In [40]:
# fazer um dicionário criando uma nova variável (novos funcionários)

novos_funcionarios = {
    "IdFuncionario":[7, 8],
    "Nome": ["Gabriel", "Helena"],
    "IdSetor": [3, 4],
    "Salario": [4500, 5300],
    "Idade": [31, 38],
    }

df_novos_funcionarios = pd.DataFrame(novos_funcionarios)

In [41]:
df_novos_funcionarios

   IdFuncionario     Nome  IdSetor  Salario  Idade
0              7  Gabriel        3     4500     31
1              8   Helena        4     5300     38

In [42]:
df_funcionarios = pd.concat([df_funcionarios, df_novos_funcionarios], ignore_index= True)

In [43]:
df_funcionarios

   IdFuncionario      Nome  IdSetor  Salario  Idade
0              1       Ana        1     4500     25
1              2     Bruno        2     6000     30
2              3    Carlos        1     4800     28
3              4     Diana        3     7500     35
4              5   Eduardo        2     5200     40
5              6  Fernanda        3     4000     26
6              7   Gabriel        3     4500     31
7              8    Helena        4     5300     38

In [44]:
df_resultado = df_funcionarios.merge(df_setores, on="IdSetor")

In [45]:
print(df_resultado[["Nome", "Setor", "Salario"]])

       Nome             Setor  Salario
0       Ana  Recursos Humanos     4500
1     Bruno        Tecnologia     6000
2    Carlos  Recursos Humanos     4800
3     Diana            Vendas     7500
4   Eduardo        Tecnologia     5200
5  Fernanda            Vendas     4000
6   Gabriel            Vendas     4500
7    Helena         Marketing     5300

In [46]:
print(df_funcionarios)

   IdFuncionario      Nome  IdSetor  Salario  Idade
0              1       Ana        1     4500     25
1              2     Bruno        2     6000     30
2              3    Carlos        1     4800     28
3              4     Diana        3     7500     35
4              5   Eduardo        2     5200     40
5              6  Fernanda        3     4000     26
6              7   Gabriel        3     4500     31
7              8    Helena        4     5300     38

### Agrupando valores

In [54]:
# usar a funçao mean para saber a média salarial de cada setor, o groupby foi p apresentar os valores

print(df_funcionarios_setor.groupby("Setor")["Salario"].mean())

Setor
Marketing           5300.000000
Recursos Humanos    4650.000000
Tecnologia          5600.000000
Vendas              5333.333333
Name: Salario, dtype: float64

### Utilizando pivot()

In [ ]:
#pede o histórico de salário - vamos converter uma coluna para cada mês 

df_historico_salarios

        Nome  Mes  Salario
0        Ana  Jan     4000
1        Ana  Fev     4200
2        Ana  Mar     4500
3      Bruno  Jan     5800
4      Bruno  Fev     5900
5      Bruno  Mar     6000
6     Carlos  Jan     4500
7     Carlos  Fev     4600
8     Carlos  Mar     4800
9      Diana  Jan     7000
10     Diana  Fev     7200
11     Diana  Mar     7500
12   Eduardo  Jan     5000
13   Eduardo  Fev     5100
14   Eduardo  Mar     5200
15  Fernanda  Jan     3800
16  Fernanda  Fev     3900
17  Fernanda  Mar     4000

In [53]:
df_historico_salarios.pivot(index="Nome", columns="Mes", values="Salario")

Mes        Fev   Jan   Mar
Nome
Ana       4200  4000  4500
Bruno     5900  5800  6000
Carlos    4600  4500  4800
Diana     7200  7000  7500
Eduardo   5100  5000  5200
Fernanda  3900  3800  4000